version: "3.4"

services:
  cicd:
    image: ldap
    command: ["go", "run", "main.go"]
    deploy:
      replicas: 1
      update_config:
        delay: 1s
        order: start-first
      restart_policy:
        condition: on-failure
